
services:
  postgres:
    image: postgres:17.4
    container_name: ds-pg-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init/01-init-database.sql:/docker-entrypoint-initdb.d/01-init-database.sql
#      - ./init/02-init-schema.sql:/docker-entrypoint-initdb.d/02-init-schema.sql
      - ds-pg-db-data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dschool" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - ds-local

volumes:
  ds-pg-db-data:
networks:
  ds-local: