
-- todo: индексы добавить


create table region
(
    id         int2 generated by default as identity not null,
    name       varchar(16)                           not null,
    created_at timestamp with time zone              not null,
    updated_at timestamp with time zone              not null,

    constraint pk__region__id primary key (id)
);


create table city
(
    id         int2 generated by default as identity not null,
    name       varchar(32)                           not null,
    region_id  int2                                  not null,
    created_at timestamp with time zone              not null,
    updated_at timestamp with time zone              not null,

    constraint pk__city__id primary key (id),
    constraint fk__city__region foreign key (region_id) references region (id)
);


create table organization
(
    id         int2 generated by default as identity not null,
    name       varchar(64)                           not null,
    city_id    int2                                  not null,
    note       varchar(256),
    created_at timestamp with time zone              not null,
    updated_at timestamp with time zone              not null,

    constraint pk__organization__id primary key (id),
    constraint fk__organization__city foreign key (city_id) references city (id)
);


create table groups
(
    id              int4 generated by default as identity not null,
    name            varchar(32)                           not null,
    organization_id int2                                  not null,
    note            varchar(256),
    created_at      timestamp with time zone              not null,
    updated_at      timestamp with time zone              not null,

    constraint pk__groups__id primary key (id),
    constraint fk__groups__organization foreign key (organization_id) references organization (id)
);


create table users
(
    id                            int4 generated by default as identity not null,
    first_name                    varchar(64)                           not null,
    middle_name                   varchar(64),
    last_name                     varchar(64)                           not null,
    phone_number                  varchar(16),
    security_code                 varchar(128),
    security_code_expiration_date timestamp with time zone,
    balance                       float8                                not null,
    version                       int4                                  not null,
    access_admin                  boolean                               not null,
    mobile_access                 boolean                               not null,
    note                          varchar(256),
    active                        boolean                               not null default true,
    created_at                    timestamp with time zone              not null,
    updated_at                    timestamp with time zone              not null,

    constraint pk__users__id primary key (id)
);


create table groups_users
(
    user_id  int4 not null,
    group_id int4 not null,

    constraint fk__groups_users__users foreign key (user_id) references users (id),
    constraint fk__groups_users__groups foreign key (group_id) references groups (id)
);


create table user_link
(
    id           int4 generated by default as identity not null,
    user_id      int4                                  not null,
    owner_id     int4                                  not null,
    receive_push boolean                               not null,
    receive_sms  boolean                               not null,
    created_at   timestamp with time zone              not null,
    updated_at   timestamp with time zone              not null,

    constraint pk__user_link__id primary key (id),
    constraint fk__user_link__users foreign key (user_id) references users (id),
    constraint fk__user_link__owners foreign key (owner_id) references users (id)
);


create table push_token
(
    id         int4 generated by default as identity not null,
    user_id    int4                                  not null,
    token      varchar(512)                          not null,
    platform   varchar(32)                           not null,
    created_at timestamp with time zone              not null,
    updated_at timestamp with time zone              not null,

    constraint pk__push_token__id primary key (id),
    constraint fk__push_token__users foreign key (user_id) references users (id)
);


create table service
(
    id          int2 generated by default as identity not null,
    name        varchar(64)                           not null,
    disposable  boolean                               not null,
    sms_notify  boolean                               not null,
    push_notify boolean                               not null,
    active      boolean                               not null default true,
    created_at  timestamp with time zone              not null,
    updated_at  timestamp with time zone              not null,

    constraint pk__service__id primary key (id)
);


create table service_to_user
(
    id             int4 generated by default as identity not null,
    user_id        int4                                  not null,
    owner_id       int4                                  not null,
    service_id     int2                                  not null,
    active_from    timestamp with time zone              not null,
    mobile_request boolean                               not null default false,
    created_at     timestamp with time zone              not null,
    updated_at     timestamp with time zone              not null,

    constraint pk__service_to_user__id primary key (id),
    constraint fk__service_to_user__users foreign key (user_id) references users (id),
    constraint fk__service_to_user__owners foreign key (owner_id) references users (id),
    constraint fk__service_to_user__service foreign key (service_id) references service (id)
);


create table controller
(
    id              int2 generated by default as identity not null,
    url             varchar(32)                           not null,
    port            int2                                  not null,
    pass_code_size  int2                                  not null default 8,
    organization_id int2                                  not null,
    active          timestamp with time zone              not null,
    note            varchar(256),
    created_at      timestamp with time zone              not null,
    updated_at      timestamp with time zone              not null,

    constraint pk__controller__id primary key (id),
    constraint fk__controller__organization foreign key (organization_id) references organization (id)
);


create table device
(
    id            int2 generated by default as identity not null,
    address       int2                                  not null,
    controller_id int2                                  not null,
    left_is_entry boolean                               not null,
    note          varchar(256),
    created_at    timestamp with time zone              not null,
    updated_at    timestamp with time zone              not null,

    constraint pk__device__id primary key (id),
    constraint fk__device__controller foreign key (controller_id) references controller (id)
);


create table event
(
    id              int8 generated by default as identity not null,
    event_type      int2                                  not null,
    direction       int2                                  not null,
    fired_at        timestamp with time zone              not null,
    user_id         int4                                  not null,
    organization_id int2                                  not null,
    controller_id   int2                                  not null,
    device_address  int2                                  not null,
    created_at      timestamp with time zone              not null,

    constraint pk__event__id primary key (id),
    constraint fk__event__users foreign key (user_id) references users (id),
    constraint fk__event__organization foreign key (organization_id) references organization (id),
    constraint fk__event__controller foreign key (controller_id) references controller (id)
);


create table pass_order
(
    id             int4 generated by default as identity not null,
    user_id        int4                                  not null,
    group_id       int4                                  not null,
    owner_id       int4                                  not null,
    pass_code      varchar(32),
    reason         varchar(32)                           not null,
    status         varchar(32)                           not null,
    mobile_request boolean                               not null default false,
    note           varchar(256),
    created_at     timestamp with time zone              not null,
    updated_at     timestamp with time zone              not null,

    constraint pk__pass_order__id primary key (id),
    constraint fk__pass_order__users foreign key (user_id) references users (id),
    constraint fk__pass_order__owners foreign key (owner_id) references users (id),
    constraint fk__pass_order__groups foreign key (group_id) references groups (id)
);

